### ISSUE TITLE
Error when loading module due to Strict MIME type checking.

### ISSUE THREAD

**Issue by TYTheBeast** [cafeed28/replugged-nitrospoof#1]
`Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.`

Is the error I get in the console when trying to load NitroSpoof.
Replugged's own error message says: `[Replugged:Plugin:NitroSpoof] TypeError: Failed to fetch dynamically imported module: replugged://plugin/replugged-nitrospoof/src/index.ts}`

I've only worked with a bit of JS and never went into much modding of the actual Discord client, so I can't solve the issue myself.
Tried to run `pnpm i` and `pnpm run build` in the plugin's folder, but nothing changed.

**Comment by cafeed28** [comment]
If you cloned the source code to `%USERPROFILE%\replugged\plugins` then move it to any other directory, e.g. `%USERPROFILE%\Development`, `pnpm run build` will copy compiled plugin to `%USERPROFILE%\replugged\plugins` and it should work

**Comment by TYTheBeast** [comment]
Now getting a different error:
`[Replugged:Plugin:NitroSpoof] TypeError: settings.init is not a function`

**Comment by cafeed28** [comment]
Try to update your replugged with `git pull`, `pnpm build` and reload Discord

**Comment by cafeed28** [comment]
Closed due to inactivity
