### ISSUE TITLE
Plugin no longer working

### ISSUE THREAD

**Issue by Weissach** [cafeed28/replugged-nitrospoof#10]
Plugin doesn't work. Settings stab is gone from the settings menu, and when you click to send a plugin in chat, it sends the ":xxxxxxx:" text.
Tried uninstalling and installing back, didn't work at all.

**Comment by cafeed28** [comment]
what version of replugged and discord are you using?

**Comment by Weissach** [comment]
Discord: [BUILD INFO] Release Channel: stable, Build Number: 183813

Replugged was on 4.1, I thought it auto-updated, but apparently not. My fault. All good, plugin functions normally.
