### ISSUE TITLE
Sending New Discord Stickers does not work

### ISSUE THREAD

**Issue by Annieeeeeeeeeeeeeeeeee** [cafeed28/replugged-nitrospoof#13]
Despite your newest update, trying to send the new stickers does nothing on my end with the plugin turned on, but i can send them normally with the plugin turned off which is rather annoying.

https://github.com/cafeed28/replugged-nitrospoof/assets/110065531/009043f8-5e50-4410-a79e-13d23aa8544c

Im using discord canary on binbows 10

**Comment by cafeed28** [comment]
Cannot reproduce on latest Discord Stable and Canary. What plugins do you use?

![image](https://github.com/cafeed28/replugged-nitrospoof/assets/62172116/1209c3a7-f2a1-4c70-ab36-0b9e0418a7d1)
![image](https://github.com/cafeed28/replugged-nitrospoof/assets/62172116/75582eda-9b9d-4f91-8d2b-a7090e8ecb88)

**Comment by Annieeeeeeeeeeeeeeeeee** [comment]
I have uninstalled all other plugins and the same thing happens.
![image](https://github.com/cafeed28/replugged-nitrospoof/assets/110065531/84869a08-b9e1-4577-8f67-ba26bf4f292e)
![image](https://github.com/cafeed28/replugged-nitrospoof/assets/110065531/21a4966a-95c6-49b4-806a-528880eb80de)

**Comment by cafeed28** [comment]
Update NitroSpoof to v2.1.4 using Updater tab, it should be fixed
![image](https://github.com/cafeed28/replugged-nitrospoof/assets/62172116/7c3766f0-c7d1-4e45-b41b-2ce72596b2a5)

**Comment by Annieeeeeeeeeeeeeeeeee** [comment]
Oh, sorry i didn't know that plugins don't update automatically oops
