### ISSUE TITLE
Stickers don't work

### ISSUE THREAD

**Issue by Yumeo0** [cafeed28/replugged-nitrospoof#14]
Sticker fails to send
![image](https://github.com/cafeed28/replugged-nitrospoof/assets/60485613/962c17a2-b28c-4e5b-a912-3dbd6cfb3f1b)

This is the error it throws in the console:
`{
    "ok": false,
    "headers": {
        "access-control-allow-credentials": "true",
        "access-control-allow-headers": "Content-Type, Authorization, X-Audit-Log-Reason, X-Track, X-Super-Properties, X-Context-Properties, X-Failed-Requests, X-Fingerprint, X-RPC-Proxy, X-Discord-Locale, X-Discord-Timezone, X-Debug-Options, x-client-trace-id, If-None-Match, X-Captcha-Key, X-Captcha-Rqtoken, X-Discord-MFA-Authorization, Range, X-RateLimit-Precision",
        "access-control-allow-methods": "POST, GET, PUT, PATCH, DELETE",
        "access-control-allow-origin": "https://discord.com",
        "alt-svc": "h3=\":443\"; ma=86400",
        "cf-cache-status": "DYNAMIC",
        "cf-ray": "7d85619d4b68c2fa-VIE",
        "content-encoding": "br",
        "content-type": "application/json",
        "date": "Fri, 16 Jun 2023 19:15:24 GMT",
        "nel": "{\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}",
        "report-to": "{\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=b8tmJrfRcPO7L5hbE8d55p7YaC9%2FbXJ5kcVidNSafhh9yDCcAIgIa1FNIzmfqxkCqa8L%2Beff0Z8g5VIwzzq8RT6Lu2r4qF2yTIWeNlYxbW8sTLf3K3usMy0dNvbv\"}],\"group\":\"cf-nel\",\"max_age\":604800}",
        "server": "cloudflare",
        "strict-transport-security": "max-age=31536000; includeSubDomains; preload",
        "via": "1.1 google",
        "x-content-type-options": "nosniff"
    },
    "body": {
        "message": "Cannot use this sticker",
        "code": 50081
    },
    "text": "{\"message\": \"Cannot use this sticker\", \"code\": 50081}",
    "status": 403
}`

**Comment by cafeed28** [comment]
Turn on verbose logging in NitroSpoof misc settings

![image](https://github.com/cafeed28/replugged-nitrospoof/assets/62172116/9df10ed6-7f37-405a-af93-e2bbaa559f2d)
then open DevTools console (ctrl+shift+i) and put this string in filter
`[Replugged:Plugin:NitroSpoof]`

![image](https://github.com/cafeed28/replugged-nitrospoof/assets/62172116/ad597c30-dd4e-47e5-a7f5-f3d14c1db0f3)
and send a screenshot of the console after you try to send the sticker

**Comment by Yumeo0** [comment]
![image](https://github.com/cafeed28/replugged-nitrospoof/assets/60485613/ee336e49-f431-4087-9f92-964e286d4ea3)

**Comment by cafeed28** [comment]
Are you using aspotrnoy's No Nitro Upsell plugin?

**Comment by Yumeo0** [comment]
No

**Comment by cafeed28** [comment]
What plugins do you use and what version of Discord and Replugged do you have?

**Comment by Yumeo0** [comment]
I'll turn every plugin off and try again. I forgot to do that before...

**Comment by Yumeo0** [comment]
Alright still doesn't work.
Discord: Stable 205806 (1e8dd98)
Replugged: v4.4.2

**Comment by cafeed28** [comment]
do you have a Nitro?

**Comment by Yumeo0** [comment]
Yes but I still have discord classic. That version doesn't even exist anymore...

**Comment by cafeed28** [comment]
I figured out that Nitro Classic doesn't allow you to use stickers everywhere, so it's a plugin issue. I will fix it
![image](https://github.com/cafeed28/replugged-nitrospoof/assets/62172116/7ee28592-d5cc-4bd0-b0ba-a071a0236122)

**Comment by cafeed28** [comment]
Update rolled out to store, update the plugin and try again

**Comment by Yumeo0** [comment]
I already tried it out manually after you closed it. Store is broken for me (Made an issue on repluggeds github). Plugin works perfectly now 👍
