### ISSUE TITLE
Support for In-line Emoji 

### ISSUE THREAD

**Issue by PlatFlat** [cafeed28/replugged-nitrospoof#15]
When inline emoji is applied to text, for example. 

Normal Behavior:
> This is a 😀 grinning face.

While using the replugged-nitrospoof plugin:
> This is a  grinning face.
😀

Those custom static emoji cannot be applied to in-line text. Normal emote (which are default, example ":grinning:") from Discord work fine.

**Comment by Yumeo0** [comment]
I don't think that is possible. Discord uses a : at the beginning and end of an emote name to symbolize an emote and then it gets replaced by an image client-side? This plugin circumvents that by sending an image instead, what that does though is limit where you can put it (just the end of the message).

**Comment by cafeed28** [comment]
Emoji spoofing just replaces the unavailable emoji with that emoji's image URL, so Discord will always display the images after the message.
