### ISSUE TITLE
Stickers don't work

### ISSUE THREAD

**Issue by Legonzaur** [cafeed28/replugged-nitrospoof#16]
# Misc information
Version of the plugin : 2.1.7
Additional plugins : none
Type of nitro : I do not have nitro
# Description of the problem

Currently, sending stickers don't work
When I click on a sticker, I would expect the plugin to send a link to the image of the sticker, or the image itself, similarly to what it does with emojis.

https://github.com/cafeed28/replugged-nitrospoof/assets/34353603/d504f556-0326-4045-9851-c82a62869aff

This is the output of the console with nitrospoof verbose logging enabled
![image](https://github.com/cafeed28/replugged-nitrospoof/assets/34353603/375aff11-aeda-49fb-9ede-a28da39e7a6f)

**Comment by cafeed28** [comment]
What version of Discord and Replugged do you have?

**Comment by Legonzaur** [comment]
Discord Stable 207472 (945c7fa)
Replugged v4.4.2

**Comment by cafeed28** [comment]
Open Network tab, open entry with your sticker id and send a screenshot of Content-Security-Policy response header
![image](https://github.com/cafeed28/replugged-nitrospoof/assets/62172116/93134455-34f8-4988-8279-a31e270c8892)

**Comment by Legonzaur** [comment]
![image](https://github.com/cafeed28/replugged-nitrospoof/assets/34353603/7950a016-100a-4124-afc4-d624766186c8)

**Comment by cafeed28** [comment]
Is this still an issue?
