### ISSUE TITLE
Instant crashing discord

### ISSUE THREAD

**Issue by SzymenL0K0** [cafeed28/replugged-nitrospoof#21]
Yea :/ just download and install this plugin. They ask me to refresh discord and its starts to instant crashing. 
![obraz](https://github.com/cafeed28/replugged-nitrospoof/assets/35821006/2ee5c123-4c9c-475d-a889-3115c377b845)
 
 discord and replugged installed today (18.09.2023) 
 Windows 10 22H2 
After PC restart it starts work but i still write it down to give info about it

**Comment by cafeed28** [comment]
Open the console (ctrl+shift+i) when it crashes and send the logs

**Comment by cafeed28** [comment]
Closed due to inactivity
