### ISSUE TITLE
короче почини

### ISSUE THREAD

**Issue by cafeed28** [cafeed28/replugged-nitrospoof#22]
![image](https://github.com/cafeed28/replugged-nitrospoof/assets/62172116/66dae602-76e7-4240-94e4-568554f4eb1c)
![image](https://github.com/cafeed28/replugged-nitrospoof/assets/62172116/ca133260-a3eb-43f3-be0f-ff854914d5c8)
![image](https://github.com/cafeed28/replugged-nitrospoof/assets/62172116/301c7caf-6f3e-4212-b8db-7747cd5cf968)

**Comment by cafeed28** [comment]
а ну еще сделай чтоб убирались дупликаты

**Comment by DiegoArmando-27** [comment]
🇵🇰

**Comment by cafeed28** [comment]
починил кароче
