### ISSUE TITLE
Screenshare in calls broken

### ISSUE THREAD

**Issue by Sleetzer** [cafeed28/replugged-nitrospoof#27]
Not allowing resolution changes or fps changes.

**Comment by cafeed28** [comment]
can't reproduce, check your settings (NitroSpoof -> Miscellaneous -> Spoof stream quality)
![image](https://github.com/user-attachments/assets/79aef91b-83fa-4a55-b0d2-2fd880e73527)

**Comment by Sleetzer** [comment]
> can't reproduce, check your settings (NitroSpoof -> Miscellaneous -> Spoof stream quality) ![image](https://private-user-images.githubusercontent.com/62172116/378095679-79aef91b-83fa-4a55-b0d2-2fd880e73527.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4MTEyMjEsIm5iZiI6MTcyOTgxMDkyMSwicGF0aCI6Ii82MjE3MjExNi8zNzgwOTU2NzktNzlhZWY5MWItODNmYS00YTU1LWIwZDItMmZkODgwZTczNTI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDIzMDIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3MDg2Y2E5ODExMTVjN2JmNDNkOTNjYmU0OTdhZmJiOTFhNTI2OTViMGJhZmIxMjUwM2MyZTBkNzk3YjM1MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.631Hy0n6Ar90SuFt-1vSRBl56YOQ7UBIJ9FO2SHrZfY)

Has been fixed since the recent update.
