### ISSUE TITLE
Drop-Down Menu in settings or reloading plugin throws a error

### ISSUE THREAD

**Issue by divine-ray** [cafeed28/replugged-nitrospoof#8]
When opening any of these (
![image](https://user-images.githubusercontent.com/29178731/226425142-b6ec7eb1-6533-45a1-9c59-411c54670eed.png)), console throws the following error: 
![image](https://user-images.githubusercontent.com/29178731/226425359-76f106ff-0b30-4a54-9eac-5fac6e324fcb.png)
![image](https://user-images.githubusercontent.com/29178731/226425399-c437ce14-26f9-42ba-9547-e81e499d1185.png)

on clicking the reload plugin button, this error occurs:
![image](https://user-images.githubusercontent.com/29178731/226425596-28b7c593-bd2b-4685-a125-7ebb0af3f0e7.png)

thanks for your time :)

**Comment by cafeed28** [comment]
cannot reproduce with canary and latest replugged 
![image](https://user-images.githubusercontent.com/62172116/226634574-13cff607-55de-4639-a546-8d445d124ee1.png)
![image](https://user-images.githubusercontent.com/62172116/226634451-f50cb02a-754c-4588-be19-1fde4bc51870.png)
![image](https://user-images.githubusercontent.com/62172116/226634778-1f5b74b7-8639-4b2e-9092-668b19f61fa0.png)

**Comment by cafeed28** [comment]
Closed due to inactivity
