### ISSUE TITLE
nitro spoof no longer starts on latest canary

### ISSUE THREAD

**Issue by kittibyte** [cafeed28/replugged-nitrospoof#9]
title explains itself, im on both latest replugged and canary at the time of writing this

![image](https://user-images.githubusercontent.com/35849198/227560470-8839cf44-31c4-4429-b78f-ea75db06aa9c.png)

**Comment by cafeed28** [comment]
cannot reproduce on latest canary and latest replugged
![image](https://user-images.githubusercontent.com/62172116/227714397-45b1dcce-2df4-4a13-a615-ad5312975821.png)
![image](https://user-images.githubusercontent.com/62172116/227714452-20aa76c9-149c-458d-8526-56f2cb92dc7a.png)

can be related to discord update, try update replugged

**Comment by kittibyte** [comment]
seems like the latest replugged update fixed this problem? very strange
